// Generated by CoffeeScript 1.8.0
(function() {
  var BubbleChart, root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BubbleChart = (function() {
    function BubbleChart(data) {
      this.hide_details = __bind(this.hide_details, this);
      this.show_details = __bind(this.show_details, this);
      this.hide_years = __bind(this.hide_years, this);
      this.display_years = __bind(this.display_years, this);
      this.move_towards_year = __bind(this.move_towards_year, this);
      this.display_by_year = __bind(this.display_by_year, this);
      this.move_towards_center = __bind(this.move_towards_center, this);
      this.display_group_all = __bind(this.display_group_all, this);
      this.start = __bind(this.start, this);
      this.create_vis = __bind(this.create_vis, this);
      this.create_nodes = __bind(this.create_nodes, this);
      var max_amount;
      this.data = data;
      this.width = 940;
      this.height = 600;
      this.tooltip = CustomTooltip("gates_tooltip", 300);
      this.view = "all";
      this.center = {
        x: this.width / 2,
        y: this.height / 2
      };
      this.year_centers = {
        "2014 Actual": {
          x: this.width / 3,
          y: this.height / 2
        },
        "2015 Proposed": {
          x: this.width / 2,
          y: this.height / 2
        },
        "2016 Proposed": {
          x: 2 * this.width / 3,
          y: this.height / 2
        }
      };
      this.change_centers = {
          "very positive":{
            x: this.width/2,
            y: this.height/2.3
          },
          "positive":{
            x: this.width/2,
            y: this.height/2.2
          },
          "somewhat positive":{
            x: this.width/2,
            y: this.height/2.1
          },
          "slightly positive":{
            x: this.width/2,
            y: this.height/2.0
          },
          "slightly negative":{
            x: this.width/2,
            y: (this.height/2.0)
          },
          "somewhat negative":{
            x: this.width/2,
            y: (this.height/1.9)
          },
          "negative":{
            x: this.width/2,
            y: (this.height/1.8)
          },
          "very negative":{
            x: this.width/2,
            y: (this.height/1.7)
          }
      };
      this.categories_centers = {
          "Legislative, Judicial, Legal":{
            x: (this.width/5)*1.3,
            y: this.height/4.5*1.5
          },
          "Health":{
            x: (this.width/5)*2.2,
            y: this.height/4.5*1.5
          },
          "Natural Resources and Environment":{
            x: (this.width/5)*3.1,
            y: this.height/4.5*1.5
          },
          "Public Safety":{
            x: (this.width/5)*1.3,
            y: (this.height/4.5) * 2.2
          },
          "Human Resources":{
            x: (this.width/5)*2.2,
            y: (this.height/4.5) * 2.2
          },
          "Elementary and Secondary Education":{
            x: (this.width/5)*3.1,
            y: (this.height/4.5)*2.2
          },
          "Transportation":{
            x: (this.width/5)*1.3,
            y: (this.height/4.5)*2.9
          },
          "Higher Education":{
            x: (this.width/5)*2.2,
            y: (this.height/4.5)*2.9
          },
          "Other":{
            x: (this.width/5)*3.1,
            y: (this.height/4.5)*2.9
          },
          "Public Debt":{
            x: (this.width/5)*3.9,
            y: (this.height/2.5)
          },
          "Reserve Fund":{
            x: (this.width/5)*3.9,
            y: (this.height/1.6666)
          }
      };
      this.fill_color = function(num){
        if(num < -0.075){
          return "#d84b2a";
        }
        else if (num < -0.05){
          return "#ee9586";
        }
        else if (num < -0.025){
          return "#e4b7b2";
        }
        else if (num < 0){
          return "#AAA";
        }
        else if (num < 0.025){
          return "#AAA";
        }
        else if (num < 0.05){
          return "#9caf84";
        }
        else if (num < 0.075){
          return "#7aa25c";
        }
        else{
          return "#557140"
        }
      };

      this.setChangeSign = function(num){
        if(num < -0.075){
          return "very negative";
        }
        else if (num < -0.05){
          return "negative";
        }
        else if (num < -0.025){
          return "somewhat negative";
        }
        else if (num < 0){
          return "slightly negative";
        }
        else if (num < 0.025){
          return "slightly positive";
        }
        else if (num < 0.05){
          return "somewhat positive";
        }
        else if (num < 0.075){
          return "positive";
        }
        else{
          return "very positive";
        }
      };

      var categories = [
        {
          "Code":"A15",
          "Category":"Other"
        },
        {
          "Code":"B75",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C00",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C80",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C81",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C82",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C85",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C90",
          "Category":"Other"
        },
        {
          "Code":"C91",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C94",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C96",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"C98",
          "Category":"Legislative, Judicial, Legal"
        },
        {
          "Code":"D05",
          "Category":"Other"
        },
        {
          "Code":"D10",
          "Category":"Other"
        },
        {
          "Code":"D11",
          "Category":"Health"
        },
        {
          "Code":"D12",
          "Category":"Health"
        },
        {
          "Code":"D13",
          "Category":"Natural Resources and Environment"
        },
        {
          "Code":"D15",
          "Category":"Other"
        },
        {
          "Code":"D15A16",
          "Category":"Public Safety"
        },
        {
          "Code":"D16",
          "Category":"Other"
        },
        {
          "Code":"D17",
          "Category":"Other"
        },
        {
          "Code":"D18",
          "Category":"Human Resources"
        },
        {
          "Code":"D25",
          "Category":"Elementary and Secondary Education"
        },
        {
          "Code":"D26",
          "Category":"Health"
        },
        {
          "Code":"D27",
          "Category":"Human Resources"
        },
        {
          "Code":"D28",
          "Category":"Other"
        },
        {
          "Code":"D38",
          "Category":"Other"
        },
        {
          "Code":"D39",
          "Category":"Other"
        },
        {
          "Code":"D40",
          "Category":"Natural Resources and Environment"
        },
        {
          "Code":"D50",
          "Category":"Public Safety"
        },
        {
          "Code":"D53",
          "Category":"Public Safety"
        },
        {
          "Code":"D55",
          "Category":"Public Safety"
        },
        {
          "Code":"D60",
          "Category":"Other"
        },
        {
          "Code":"D78",
          "Category":"Health"
        },
        {
          "Code":"D79",
          "Category":"Health"
        },
        {
          "Code":"D80",
          "Category":"Health"
        },
        {
          "Code":"D90",
          "Category":"Other"
        },
        {
          "Code":"D99",
          "Category":"Other"
        },
        {
          "Code":"E00",
          "Category":"Other"
        },
        {
          "Code":"E20",
          "Category":"Other"
        },
        {
          "Code":"E50",
          "Category":"Other"
        },
        {
          "Code":"E75",
          "Category":"Other"
        },
        {
          "Code":"E80",
          "Category":"Other"
        },
        {
          "Code":"F10",
          "Category":"Other"
        },
        {
          "Code":"F50",
          "Category":"Other"
        },
        {
          "Code":"G20",
          "Category":"Other"
        },
        {
          "Code":"G50",
          "Category":"Other"
        },
        {
          "Code":"H00",
          "Category":"Other"
        },
        {
          "Code":"J00",
          "Category":"Transportation"
        },
        {
          "Code":"K00",
          "Category":"Natural Resources and Environment"
        },
        {
          "Code":"L00",
          "Category":"Natural Resources and Environment"
        },
        {
          "Code":"M00",
          "Category":"Health"
        },
        {
          "Code":"N00",
          "Category":"Human Resources"
        },
        {
          "Code":"P00",
          "Category":"Other"
        },
        {
          "Code":"Q00",
          "Category":"Public Safety"
        },
        {
          "Code":"R00",
          "Category":"Elementary and Secondary Education"
        },
        {
          "Code":"R13",
          "Category":"Higher Education"
        },
        {
          "Code":"R14",
          "Category":"Higher Education"
        },
        {
          "Code":"R15",
          "Category":"Other"
        },
        {
          "Code":"R30",
          "Category":"Higher Education"
        },
        {
          "Code":"R62",
          "Category":"Higher Education"
        },
        {
          "Code":"R95",
          "Category":"Higher Education"
        },
        {
          "Code":"R99",
          "Category":"Elementary and Secondary Education"
        },
        {
          "Code":"S00",
          "Category":"Human Resources"
        },
        {
          "Code":"S50",
          "Category":"Other"
        },
        {
          "Code":"T00",
          "Category":"Other"
        },
        {
          "Code":"T50",
          "Category":"Other"
        },
        {
          "Code":"U00",
          "Category":"Natural Resources and Environment"
        },
        {
          "Code":"V00",
          "Category":"Public Safety"
        },
        {
          "Code":"W00",
          "Category":"Public Safety"
        },
        {
          "Code":"X00",
          "Category":"Public Debt"
        },
        {
          "Code":"Y01",
          "Category":"Reserve Fund"
        }
      ];

      this.getCategory = function(agency_code){
        for(var i = 0; i < categories.length; i++){
          if(categories[i]["Code"] == agency_code){
            return categories[i]["Category"];
          }
        }
        return "Other";
      };

      this.layout_gravity = -0.02;
      this.damper = 0.1;
      this.vis = null;
      this.nodes = [];
      this.force = null;
      this.circles = null;
      max_amount = d3.max(this.data, function(d) {
        return parseInt(d.current_budget);
      });
      this.radius_scale = d3.scale.pow().exponent(0.5).domain([0, max_amount]).range([2, 85]);
      this.create_nodes();
      this.create_vis();
    }

    BubbleChart.prototype.create_nodes = function() {
      this.data.forEach((function(_this) {
        return function(d) {
          var node;
          node = {
            id: d.agency_code,
            radius: _this.radius_scale(parseInt(d.current_budget)),
            value: d.current_budget,
            name: d.agency_name,
            //department: d.department,
            group: d.agency_name,
            year: d.year ? d.year : "2016 Proposed",
            change: d.change,
            category: _this.getCategory(d.agency_code),
            change_sign: _this.setChangeSign(d.change),//d.change < 0 ? "negative": "positive",
            x: Math.random() * 900,
            y: Math.random() * 800
          };
          return _this.nodes.push(node);
        };
      })(this));
      return this.nodes.sort(function(a, b) {
        return b.change - a.change;
      });
    };

    BubbleChart.prototype.create_vis = function() {
      var that;
      this.vis = d3.select("#vis").append("svg").attr("width", this.width).attr("height", this.height).attr("id", "svg_vis");
      this.circles = this.vis.selectAll("circle").data(this.nodes, function(d) {
        return d.id;
      });
      that = this;
      this.circles.enter().append("circle").attr("r", 0).attr("fill", (function(_this) {
        return function(d) {
          return _this.fill_color(d.change);
        };
      })(this)).attr("stroke-width", 1).attr("stroke", (function(_this) {
        return function(d) {
          return d3.rgb(_this.fill_color(d.change)).darker();
        };
      })(this)).attr("id", function(d) {
        return "bubble_" + d.agency_code;
      }).on("mouseover", function(d, i) {
        return that.show_details(d, i, this);
      }).on("mouseout", function(d, i) {
        return that.hide_details(d, i, this);
      });
      return this.circles.transition().duration(3000).attr("r", function(d) {
        return d.radius;
      });
    };

    BubbleChart.prototype.charge = function(d) {
      return -Math.pow(d.radius, 2.0) / 6;
    };

    BubbleChart.prototype.start = function() {
      return this.force = d3.layout.force().nodes(this.nodes).size([this.width, this.height]);
    };

    BubbleChart.prototype.display_group_all = function() {
      this.view = "all";
      this.force.gravity(this.layout_gravity).charge(this.charge).friction(0.9).on("tick", (function(_this) {
        return function(e) {
          return _this.circles.each(_this.move_towards_center(e.alpha)).attr("cx", function(d) {
            return d.x;
          }).attr("cy", function(d) {
            return d.y;
          });
        };
      })(this));
      this.force.start();
      return this.hide_years();
    };

    BubbleChart.prototype.move_towards_center = function(alpha) {
      return (function(_this) {
        return function(d) {
          var target;
          target = _this.year_centers[d.year];
          d.x = d.x + (_this.center.x - d.x) * (_this.damper + 0.02) * alpha;
          return d.y = d.y + (_this.center.y - d.y) * (_this.damper + 0.02) * alpha;
        };
      })(this);
    };

    BubbleChart.prototype.display_by_change = function() {
      this.force.gravity(this.layout_gravity).charge(this.charge).friction(.975).on("tick", (function(_this) {
        return function(e) {

         // console.log(_this.force.alpha());
        //  if (_this.force.alpha() <= 0.00506){
         //   _this.force.alpha(0.00506);
        //  }
          return _this.circles.each(_this.move_towards_change(e.alpha)).attr("cy", function(d) {
            return d.y;
          }).attr("cx", function(d) {
            return d.x;
          });
        };
      })(this));
      this.hide_category();
      this.force.start();
      return this.display_change();
    };

    BubbleChart.prototype.move_towards_change = function(alpha) {
      return (function(_this) {
        return function(d) {
          var target;
          target = _this.change_centers[d.change_sign];
          d.x = d.x + (target.x - d.x) * (_this.damper + 0.01) * alpha * 1.05;
          return d.y = d.y + (target.y - d.y) * (_this.damper + 0.01) * alpha * 1.05;
        };
      })(this);
    };

    BubbleChart.prototype.display_by_category = function() {
      this.force.gravity(this.layout_gravity).charge(this.charge).friction(.975).on("tick", (function(_this) {
        return function(e) {

         // console.log(_this.force.alpha());
        //  if (_this.force.alpha() <= 0.00506){
         //   _this.force.alpha(0.00506);
        //  }
          return _this.circles.each(_this.move_towards_category(e.alpha)).attr("cy", function(d) {
            return d.y;
          }).attr("cx", function(d) {
            return d.x;
          });
        };
      })(this));
      this.hide_change();
      this.force.start();
      return this.display_category();
    };

    BubbleChart.prototype.move_towards_category = function(alpha) {
      return (function(_this) {
        return function(d) {
          var target;
          target = _this.categories_centers[d.category];
          d.x = d.x + (target.x - d.x) * (_this.damper + 0.01) * alpha * 1.05;
          return d.y = d.y + (target.y - d.y) * (_this.damper + 0.01) * alpha * 1.05;
        };
      })(this);
    };

    BubbleChart.prototype.display_change = function() {
      /*var change, change_data, change_y;
      this.view = "change";
      change_y = {
        "Biggest Budget Increases": (this.height / 3),
        "Largest Budget Decreases": (this.height / 3)*2
      };
      change_data = d3.keys(change_y);
      change = this.vis.selectAll(".change").data(change_data);
      return change.enter().append("text").attr("class", "change").attr("y", (function(_this) {
        return function(d) {
          return change_y[d];
        };
      })(this)).attr("x", 40).attr("text-anchor", "middle").text(function(d) {
        return d;
      });*/
      this.vis.append('text').text("Largest Budget Increases").style("text-anchor", "middle").attr('class', 'change-text').attr('x', this.width/2).attr('y', this.height/20);
      this.vis.append('text').text("Largest Budget Cuts").style("text-anchor", "middle").attr('class', 'change-text').attr('x', this.width/2).attr('y', (this.height/20)*19.5);
    };

    BubbleChart.prototype.display_category = function() {
      var category, category_data, category_y;
      this.view = "category";
      category_locations = {
          "Legislative, Judicial, Legal":{
            x: (this.width/8),
            y: this.height/15
          },
          "Health":{
            x: (this.width/5)*2.1,
            y: this.height/15
          },
          "Natural Resources and Environment":{
            x: (this.width/5)*3.5,
            y: this.height/15
          },
          "Public Safety":{
            x: (this.width/8),
            y: (this.height/2.8)
          },
          "Human Resources":{
            x: (this.width/5)*2.1,
            y: (this.height/2.8)
          },
          "Elementary and Secondary Education":{
            x: (this.width/5)*3.5,
            y: (this.height/2.8)
          },
          "Transportation":{
            x: (this.width/8),
            y: (this.height/4.5)*3
          },
          "Higher Education":{
            x: (this.width/5)*2.1,
            y: (this.height/4.5)*3
          },
          "Other":{
            x: (this.width/5)*3.5,
            y: (this.height/4.5)*3
          },
          "Public Debt":{
            x: (this.width/5)*4.7,
            y: (this.height/3.6)
          },
          "Reserve Fund":{
            x: (this.width/5)*4.7,
            y: (this.height/1.6666)
          }
      };
      category_data = d3.keys(category_locations);
      category = this.vis.selectAll(".category").data(category_data);
      return category.enter().append("text").attr("class", "category").attr("y", (function(_this) {
        return function(d) {
          console.log(category_locations[d]["y"]);
          return category_locations[d]["y"];
        };
      })(this)).attr("x", (function(_this) {
        return function(d) {
          console.log(category_locations[d]["x"]);
          return category_locations[d]["x"];
        };
      })(this)).attr("text-anchor", "middle").text(function(d) {
        return d;
      });
    };

    BubbleChart.prototype.display_by_year = function() {
      this.force.gravity(this.layout_gravity).charge(this.charge).friction(0.9).on("tick", (function(_this) {
        return function(e) {
          return _this.circles.each(_this.move_towards_year(e.alpha)).attr("cx", function(d) {
            return d.x;
          }).attr("cy", function(d) {
            return d.y;
          });
        };
      })(this));
      this.force.start();
      return this.display_years();
    };

    BubbleChart.prototype.move_towards_year = function(alpha) {
      return (function(_this) {
        return function(d) {
          var target;
          target = _this.year_centers[d.year];
          d.x = d.x + (target.x - d.x) * (_this.damper + 0.02) * alpha * 1.1;
          return d.y = d.y + (target.y - d.y) * (_this.damper + 0.02) * alpha * 1.1;
        };
      })(this);
    };

    BubbleChart.prototype.display_years = function() {
      var years, years_data, years_x;
      this.view = "year";
      years_x = {
        "2014 Actual": 160,
        "2015 Proposed": this.width / 2,
        "2016 Proposed": this.width - 160
      };
      years_data = d3.keys(years_x);
      years = this.vis.selectAll(".years").data(years_data);
      return years.enter().append("text").attr("class", "years").attr("x", (function(_this) {
        return function(d) {
          return years_x[d];
        };
      })(this)).attr("y", 40).attr("text-anchor", "middle").text(function(d) {
        return d;
      });
    };

    BubbleChart.prototype.format_number = function(n, decimals){
      var s, remainder, num, negativePrefix, negativeSuffix, prefix, suffix;
      suffix = ""
      negativePrefix = ""
      negativeSuffix = ""
      if (n < 0) {
        negativePrefix = "";
        negativeSuffix = " in income"
        n = -n
      };
      
      if (n >= 1000000000000) {
          suffix = " trillion"
          n = n / 1000000000000
          decimals = 3
      } else if (n >= 1000000000) {
          suffix = " billion"
          n = n / 1000000000
          decimals = 3
      } else if (n >= 1000000) {
          suffix = " million"
          n = n / 1000000
          decimals = 2
      } 
      else if (n >= 1000) {
          suffix = ""
          n = n
          decimals = 0
      } 
      
      
      prefix = ""
      if (decimals > 0) {
          if (n<1) {prefix = "0"};
          s = String(Math.round(n * (Math.pow(10,decimals))));
          if (s < 10) {
              remainder = "0" + s.substr(s.length-(decimals),decimals);
              num = "";
          } else{
              remainder = s.substr(s.length-(decimals),decimals);
              num = s.substr(0,s.length - decimals);
          }
          
          
          return  negativePrefix + prefix + num.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,") + "." + remainder + suffix + negativeSuffix;
      } else {
          s = String(Math.round(n));
          s = s.replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,");
          return  negativePrefix + s + suffix + negativeSuffix;
      }
  };

    BubbleChart.prototype.hide_years = function() {
      var years;
      return years = this.vis.selectAll(".years").remove();
    };
    BubbleChart.prototype.hide_category = function() {
      var category;
      return category = this.vis.selectAll(".category").remove();
    };

    BubbleChart.prototype.hide_change = function() {
      this.vis.selectAll(".change-text").remove();
    };

    BubbleChart.prototype.show_details = function(data, i, element) {
      var content;
      d3.select(element).attr("stroke", "black");

      //content = "<div style='text-align:center;'><small style='color:#555;'>" + data.department + "</small><hr>";
      content = "<p style='font-size:18px; margin-top:5px; font-weight:100;'> " + data.name + "</p></div>";
      content += "<p style='float:left; font-weight:700; font-size:16px'> $" + (this.format_number(data.value)) + "</p>";
      content += "<p style='float:right; font-size:16px; font-weight:700; color:" + (data.change > 0? "#7aa25c": "#97341d") + ";'> " + ((data.change > 0)? "+": "") + Math.round(data.change * 10000) / 100 + "%</p>";//(data.change>0)? "#7aa25c": "#97341d" + ";'> " + Math.round(data.change * 1000000) / 10000 + "%</p>";
      return this.tooltip.showTooltip(content, d3.event);
    };

    BubbleChart.prototype.hide_details = function(data, i, element) {
      d3.select(element).attr("stroke", (function(_this) {
        return function(d) {
          return d3.rgb(_this.fill_color(d.change)).darker();
        };
      })(this));
      return this.tooltip.hideTooltip();
    };

    return BubbleChart;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  var init = $(function() {
    var chart, render_vis;
    chart = null;
    render_vis = function(csv) {
      chart = new BubbleChart(csv);
      chart.start();

      $("#percentChange").on("click", function(){
        $(".radio-group").removeClass("active");
        $(this).parent().addClass("active");
        return root.display_change();
      });

      $("#agencyCategory").on("click", function(){
        $(".radio-group").removeClass("active");
        $(this).parent().addClass("active");
        return root.display_category();
      });

      return root.display_change();
    };
    root.display_all = (function(_this) {
      return function() {
        return chart.display_group_all();
      };
    })(this);
    root.display_year = (function(_this) {
      return function() {
        return chart.display_by_year();
      };
    })(this);
    root.display_change = (function(_this) {
      return function() {
        return chart.display_by_change();
      };
    })(this);
    root.display_category = (function(_this) {
      return function() {
        return chart.display_by_category();
      };
    })(this);
    root.toggle_view = (function(_this) {
      return function(view_type) {
        if (view_type === 'year') {
          return root.display_change();
        } else {
          return root.display_all();
        }
      };
    })(this);

    return d3.json("data/budget.json", render_vis);
  });

}).call(this);